const sb=window.supabase.createClient(WOND_SUPABASE.url,WOND_SUPABASE.anonKey);const $=s=>document.querySelector(s);const bucket=WOND_SUPABASE.bucket;
function status(id,msg){$(id).textContent=msg}function pathSafe(n){return n.replace(/[^a-zA-Z0-9._-]/g,'_')}
async function refreshDocs(){const {data,error}=await sb.from('country_documents').select('*').order('country_code');if(error)return status('#docStatus',error.message);$('#docList').innerHTML=(data||[]).map(d=>`<div class="list-item"><span><b>${d.country_code}</b> — ${d.title}</span><button class="save danger" data-del-doc="${d.id}">Smazat</button></div>`).join('')||'<div class="small">Žádné dokumenty.</div>';document.querySelectorAll('[data-del-doc]').forEach(b=>b.onclick=async()=>{const id=b.dataset.delDoc;const row=data.find(x=>x.id===id);await sb.from('country_documents').delete().eq('id',id);if(row?.storage_path)await sb.storage.from(bucket).remove([row.storage_path]);refreshDocs()})}
async function refreshIds(){const {data,error}=await sb.from('company_identifiers').select('*').order('country_code');if(error)return status('#idStatus',error.message);$('#idList').innerHTML=(data||[]).map(d=>`<div class="list-item"><span><b>${d.country_code}</b> — ${d.label}: ${d.value}</span><button class="save danger" data-del-id="${d.id}">Smazat</button></div>`).join('')||'<div class="small">Žádné údaje.</div>';document.querySelectorAll('[data-del-id]').forEach(b=>b.onclick=async()=>{await sb.from('company_identifiers').delete().eq('id',b.dataset.delId);refreshIds()})}
async function load(){const {data:{session}}=await sb.auth.getSession();if(!session){$('#login').hidden=false;$('#app').hidden=true;return}$('#login').hidden=true;$('#app').hidden=false;$('#userEmail').textContent=session.user.email||'';refreshDocs();refreshIds()}
$('#loginBtn').onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)status('#loginStatus',error.message);else load()};$('#password').onkeydown=e=>{if(e.key==='Enter')$('#loginBtn').click()};$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();load()};document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.admin-pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab-'+b.dataset.tab).classList.add('active')});
$('#uploadPhoto').onclick=async()=>{const f=$('#photo').files[0];if(!f)return status('#photoStatus','Vyber fotografii.');const p='main-photo/'+Date.now()+'_'+pathSafe(f.name);status('#photoStatus','Nahrávám…');const up=await sb.storage.from(bucket).upload(p,f,{upsert:false,contentType:f.type});if(up.error)return status('#photoStatus',up.error.message);const pub=sb.storage.from(bucket).getPublicUrl(p).data.publicUrl;await sb.from('site_media').delete().eq('slot','main_photo');const ins=await sb.from('site_media').insert({slot:'main_photo',public_url:pub,storage_path:p});status('#photoStatus',ins.error?ins.error.message:'Hlavní fotografie byla aktualizována.');};
$('#uploadDoc').onclick=async()=>{const f=$('#docFile').files[0],code=$('#docCountry').value,title=$('#docTitle').value.trim()||'Ceník služeb';if(!f)return status('#docStatus','Vyber PDF.');const p='documents/'+code+'/'+Date.now()+'_'+pathSafe(f.name);status('#docStatus','Nahrávám…');const up=await sb.storage.from(bucket).upload(p,f,{upsert:false,contentType:'application/pdf'});if(up.error)return status('#docStatus',up.error.message);const pub=sb.storage.from(bucket).getPublicUrl(p).data.publicUrl;const ins=await sb.from('country_documents').insert({country_code:code,title,public_url:pub,storage_path:p,published:true});status('#docStatus',ins.error?ins.error.message:'PDF bylo nahráno.');$('#docFile').value='';refreshDocs()};
$('#saveId').onclick=async()=>{const country=$('#idCountry').value,label=$('#idLabel').value.trim(),value=$('#idValue').value.trim();if(!label||!value)return status('#idStatus','Vyplň název i hodnotu.');const r=await sb.from('company_identifiers').insert({country_code:country,label,value});status('#idStatus',r.error?r.error.message:'Údaj uložen.');$('#idLabel').value='';$('#idValue').value='';refreshIds()};load();
