const C={
 CZ:{name:'Česko',currency:'Kč',vat:.21, cities:['Brno','Praha','Ostrava','Plzeň','Olomouc','Kuřim','Rosice','Ivančice','Židlochovice','Blansko','Vyškov']},
 SI:{name:'Slovenija',currency:'€',vat:.22,cities:['Ljubljana','Maribor','Celje','Kranj','Koper','Novo mesto','Ptuj','Murska Sobota','Nova Gorica']},
 SK:{name:'Slovensko',currency:'€',vat:.23,cities:['Bratislava','Košice','Prešov','Žilina','Nitra','Trnava','Trenčín']},
 DE:{name:'Deutschland',currency:'€',vat:.19,cities:['Berlin','München','Hamburg','Köln','Frankfurt','Stuttgart','Dresden']},
 PL:{name:'Polska',currency:'zł',vat:.23,cities:['Warszawa','Kraków','Wrocław','Poznań','Gdańsk','Katowice']},
 HU:{name:'Magyarország',currency:'Ft',vat:.27,cities:['Budapest','Debrecen','Szeged','Pécs','Győr']},
 HR:{name:'Hrvatska',currency:'€',vat:.25,cities:['Zagreb','Split','Rijeka','Osijek','Zadar']},
 RO:{name:'România',currency:'lei',vat:.21,cities:['București','Cluj-Napoca','Timișoara','Iași','Brașov']},
 UA:{name:'Україна',currency:'₴',vat:.20,cities:['Київ','Львів','Ужгород','Одеса','Івано-Франківськ','Чернівці']},
 GB:{name:'United Kingdom',currency:'£',vat:.20,cities:['London','Birmingham','Manchester','Leeds','Bristol']}
};
const BASE=[
['Elektroinstalace',[['Elektro bod (zásuvka / vypínač)',450,'Št'],['Další elektro bod',350,'Št'],['Světelný bod',350,'Št'],['Uložení kabelu v trubce',90,'M'],['Sekání a zapravení drážek',220,'M'],['Jednoduchý vypínač',300,'Št'],['Dvojitý vypínač',400,'Št'],['Jednoduchá zásuvka',300,'Št'],['Dvojitá zásuvka',400,'Št'],['USB zásuvka',450,'Št'],['RJ45 zásuvka',400,'Št'],['TV zásuvka',400,'Št'],['Montáž svítidla',400,'Št'],['LED svítidlo',450,'Št'],['Stmívač',450,'Št']]],
['Voda a kanalizace',[['PPR potrubí',180,'M'],['ALUPEX potrubí',220,'M'],['Kanalizační potrubí',250,'M'],['Vodní bod teplá + studená',650,'Št'],['Dvojitý vodní bod',1100,'Št'],['Přípojka pro pračku',750,'Št'],['Přípojka pro myčku',750,'Št'],['Přípojka pro bojler',1000,'Št'],['Montáž bojleru do 100 l',2000,'Št'],['Montáž bojleru 100–200 l',2800,'Št'],['Montáž sanitárního vybavení',750,'Št'],['Rozdělovač',2000,'Št'],['Vodní filtr',700,'Št'],['Redukční ventil',1000,'Št']]],
['Rozvaděče a ochrany',[['Rozvaděč 24 modulů',11000,'Št'],['Rozvaděč 36 modulů',14000,'Št'],['Rozvaděč 48 modulů',18000,'Št'],['Rozvaděč 72 modulů',25000,'Št'],['Přepěťová ochrana SPD typ 2',2800,'Št'],['Relé / ochrana napětí',2800,'Št'],['Jistič',350,'Št'],['Proudový chránič FI/RCD',1400,'Št'],['RCBO kombinace',1300,'Št']]],
['Kontroly a revize',[['Základní kontrola elektroinstalace',1200,'Št'],['Vizuální kontrola',900,'Št'],['Revizní zpráva',0,'']]],
['Výjezd',[['Výjezd na místo do 50 km',500,'Št']]]
];
const $=s=>document.querySelector(s);let data={};
function fmt(n,code){return new Intl.NumberFormat(code==='CZ'?'cs-CZ':code==='UA'?'uk-UA':code==='PL'?'pl-PL':code==='HU'?'hu-HU':code==='RO'?'ro-RO':'de-DE',{maximumFractionDigits:0}).format(n)+' '+C[code].currency}
function renderPrices(){const code=$('#priceCountry').value,city=$('#priceCity').value,mode=$('#vatMode').value,c=C[code];$('#priceMeta').textContent=`${city} · ${c.name} · DPH ${Math.round(c.vat*100)} % · Ceny jsou orientační a mohou být upraveny podle rozsahu zakázky.`;$('#priceGrid').innerHTML=BASE.map(([title,rows])=>`<article class="price-card"><h3>${title}</h3><table><thead><tr><th>Služba</th><th>Bez DPH</th><th>S DPH</th></tr></thead><tbody>${rows.map(([name,base,unit])=>{if(!base)return `<tr><td>${name}</td><td colspan="2">dle rozsahu</td></tr>`;let net=base,gross=base*(1+c.vat);return `<tr><td>${name}${unit?` <small>(${unit})</small>`:''}</td><td>${mode==='gross'?'—':fmt(net,code)}</td><td>${mode==='net'?'—':fmt(gross,code)}</td></tr>`}).join('')}</tbody></table></article>`).join('')}
function init(){Object.entries(C).forEach(([k,v])=>$('#priceCountry').insertAdjacentHTML('beforeend',`<option value="${k}">${v.name}</option>`));$('#priceCountry').value='CZ';function cities(){const c=C[$('#priceCountry').value];$('#priceCity').innerHTML=c.cities.map(x=>`<option>${x}</option>`).join('');renderPrices()}$('#priceCountry').addEventListener('change',cities);$('#priceCity').addEventListener('change',renderPrices);$('#vatMode').addEventListener('change',renderPrices);cities();$('#year').textContent=new Date().getFullYear();loadSupabase();$('#menuBtn').addEventListener('click',()=>$('#mainNav').classList.toggle('open'))}
async function loadSupabase(){try{const sb=window.supabase.createClient(WOND_SUPABASE.url,WOND_SUPABASE.anonKey);const {data:media}=await sb.from('site_media').select('*').eq('slot','main_photo').maybeSingle();if(media?.public_url){$('#mainPhoto').src=media.public_url;$('#galleryMainPhoto').src=media.public_url}const {data:docs}=await sb.from('country_documents').select('*').eq('published',true).order('country_code');if(docs?.length)$('#documents').innerHTML=docs.map(d=>`<article class="document-card"><h3>${C[d.country_code]?.name||d.country_code}</h3><p>${d.title||'Ceník / dokument'}</p><a href="${d.public_url}" target="_blank" rel="noopener">Otevřít dokument</a></article>`).join('');const {data:ids}=await sb.from('company_identifiers').select('*').order('country_code');if(ids?.length)$('#companyIds').innerHTML=ids.map(x=>`<div class="id-row"><span>${x.label}</span><b>${x.value}</b></div>`).join('')}catch(e){console.warn('Online data nejsou dostupná:',e.message)}}init();
