(() => {
  const cfg=window.WOND_SUPABASE||{};
  const configured=cfg.url && cfg.anonKey && !cfg.url.includes('PASTE_') && !cfg.anonKey.includes('PASTE_');
  const sb=window.supabase && configured ? window.supabase.createClient(cfg.url,cfg.anonKey) : null;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const langs=window.WOND_LANGS;
  let lang=getLang(), session=null, profile=null;
  let countries=window.WOND_COUNTRIES||[];
  let services=window.WOND_PRICE_ITEMS||[];
  let translations=window.WOND_PRICE_TRANSLATIONS||{};
  let localPrices=window.WOND_LOCAL_PRICES||{};
  const ui={
    uk:{country:'Країна',price:'Ціна',service:'Робота',currency:'Валюта',without:'Без ПДВ',with:'З ПДВ',both:'Обидва',prices_admin:'Ціни по країнах',price_country:'Країна для цін',translations_admin:'Переклади робіт',translation_lang:'Мова перекладів',save_prices:'Зберегти ціни',save_translations:'Зберегти переклади',category:'Категорія',unit:'Одиниця'},
    cs:{country:'Země',price:'Cena',service:'Služba',currency:'Měna',without:'Bez DPH',with:'Včetně DPH',both:'Obojí',prices_admin:'Ceny podle zemí',price_country:'Země pro ceny',translations_admin:'Překlady služeb',translation_lang:'Jazyk překladů',save_prices:'Uložit ceny',save_translations:'Uložit překlady',category:'Kategorie',unit:'Jednotka'},
    sl:{country:'Država',price:'Cena',service:'Storitev',currency:'Valuta',without:'Brez DDV',with:'Z DDV',both:'Oboje',prices_admin:'Cene po državah',price_country:'Država za cene',translations_admin:'Prevodi storitev',translation_lang:'Jezik prevodov',save_prices:'Shrani cene',save_translations:'Shrani prevode',category:'Kategorija',unit:'Enota'},
    sk:{country:'Krajina',price:'Cena',service:'Služba',currency:'Mena',without:'Bez DPH',with:'S DPH',both:'Oboje',prices_admin:'Ceny podľa krajín',price_country:'Krajina pre ceny',translations_admin:'Preklady služieb',translation_lang:'Jazyk prekladov',save_prices:'Uložiť ceny',save_translations:'Uložiť preklady',category:'Kategória',unit:'Jednotka'},
    de:{country:'Land',price:'Preis',service:'Leistung',currency:'Währung',without:'Ohne MwSt.',with:'Inkl. MwSt.',both:'Beides',prices_admin:'Preise nach Ländern',price_country:'Land für Preise',translations_admin:'Übersetzungen der Leistungen',translation_lang:'Sprache der Übersetzungen',save_prices:'Preise speichern',save_translations:'Übersetzungen speichern',category:'Kategorie',unit:'Einheit'},
    en:{country:'Country',price:'Price',service:'Service',currency:'Currency',without:'Without VAT',with:'With VAT',both:'Both',prices_admin:'Prices by country',price_country:'Country for prices',translations_admin:'Service translations',translation_lang:'Translation language',save_prices:'Save prices',save_translations:'Save translations',category:'Category',unit:'Unit'},
    hr:{country:'Država',price:'Cijena',service:'Usluga',currency:'Valuta',without:'Bez PDV-a',with:'S PDV-om',both:'Oboje',prices_admin:'Cijene po državama',price_country:'Država za cijene',translations_admin:'Prijevodi usluga',translation_lang:'Jezik prijevoda',save_prices:'Spremi cijene',save_translations:'Spremi prijevode',category:'Kategorija',unit:'Jedinica'},
    sr:{country:'Država',price:'Cena',service:'Usluga',currency:'Valuta',without:'Bez PDV-a',with:'Sa PDV-om',both:'Oboje',prices_admin:'Cene po državama',price_country:'Država za cene',translations_admin:'Prevodi usluga',translation_lang:'Jezik prevoda',save_prices:'Sačuvaj cene',save_translations:'Sačuvaj prevode',category:'Kategorija',unit:'Jedinica'},
    it:{country:'Paese',price:'Prezzo',service:'Servizio',currency:'Valuta',without:'Senza IVA',with:'Con IVA',both:'Entrambi',prices_admin:'Prezzi per paese',price_country:'Paese per i prezzi',translations_admin:'Traduzioni dei servizi',translation_lang:'Lingua delle traduzioni',save_prices:'Salva prezzi',save_translations:'Salva traduzioni',category:'Categoria',unit:'Unità'},
    hu:{country:'Ország',price:'Ár',service:'Szolgáltatás',currency:'Pénznem',without:'ÁFA nélkül',with:'ÁFÁ-val',both:'Mindkettő',prices_admin:'Országonkénti árak',price_country:'Árlista országa',translations_admin:'Szolgáltatásfordítások',translation_lang:'Fordítás nyelve',save_prices:'Árak mentése',save_translations:'Fordítások mentése',category:'Kategória',unit:'Egység'},
    pl:{country:'Kraj',price:'Cena',service:'Usługa',currency:'Waluta',without:'Bez VAT',with:'Z VAT',both:'Obie',prices_admin:'Ceny według krajów',price_country:'Kraj dla cen',translations_admin:'Tłumaczenia usług',translation_lang:'Język tłumaczeń',save_prices:'Zapisz ceny',save_translations:'Zapisz tłumaczenia',category:'Kategoria',unit:'Jednostka'},
    ro:{country:'Țară',price:'Preț',service:'Serviciu',currency:'Monedă',without:'Fără TVA',with:'Cu TVA',both:'Ambele',prices_admin:'Prețuri pe țări',price_country:'Țara pentru prețuri',translations_admin:'Traduceri servicii',translation_lang:'Limba traducerilor',save_prices:'Salvează prețurile',save_translations:'Salvează traducerile',category:'Categorie',unit:'Unitate'}
  };
  const t=(key,fallback='') => (window.WOND_TRANSLATIONS[lang]||{})[key] || (window.WOND_TRANSLATIONS.cs||{})[key] || fallback || key;
  const u=k=>ui[lang]?.[k]||ui.en[k]||k;
  function getLang(){const q=new URLSearchParams(location.search).get('lang');if(q&&langs.includes(q))return q;const saved=localStorage.getItem('wond-lang');if(saved&&langs.includes(saved))return saved;const n=(navigator.language||'cs').slice(0,2);return langs.includes(n)?n:'cs';}
  function countryName(code){return window.WOND_COUNTRY_NAMES?.[lang]?.[code]||countries.find(c=>c.code===code)?.name||code;}
  function setLang(l){lang=langs.includes(l)?l:'cs';localStorage.setItem('wond-lang',lang);const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState({},'',url);document.documentElement.lang=lang;document.title=`WOND — ${t('nav_services')}`;$$('[data-i18n]').forEach(el=>el.innerHTML=t(el.dataset.i18n));$('#language').value=lang;renderCountrySelect();renderPrices();}
  const langSelect=$('#language'); langs.forEach(l=>{const o=document.createElement('option');o.value=l;o.textContent=window.WOND_TRANSLATIONS[l].name;langSelect.append(o);}); langSelect.addEventListener('change',e=>setLang(e.target.value));
  function renderCountrySelect(){const sel=$('#price-country');if(!sel)return;const current=sel.value||localStorage.getItem('wond-country')||'CZ';sel.innerHTML='';countries.filter(c=>c.active!==false).forEach(c=>{const o=document.createElement('option');o.value=c.code;o.textContent=`${countryName(c.code)} — ${c.currency}`;sel.append(o);});sel.value=countries.some(c=>c.code===current)?current:'CZ';localStorage.setItem('wond-country',sel.value);const vat=$('#vat-mode');if(vat){vat.options[0].textContent=u('without');vat.options[1].textContent=u('with');vat.options[2].textContent=u('both');}}
  function serviceName(key,raw){return translations[key]?.[lang]||translations[key]?.en||raw;}
  function fmt(n,c){return new Intl.NumberFormat(lang,{minimumFractionDigits:c==='HUF'?0:0,maximumFractionDigits:c==='HUF'?0:2}).format(n)+' '+c;}
  function renderPrices(){const grid=$('#price-grid');if(!grid)return;const mode=$('#vat-mode')?.value||'net';const code=$('#price-country')?.value||'CZ';const country=countries.find(c=>c.code===code)||countries[0];if(!country)return;const groups={};services.filter(s=>s.active!==false).forEach(s=>(groups[s.category]??=[]).push(s));grid.innerHTML='';for(const [cat,rows] of Object.entries(groups)){const card=document.createElement('div');card.className='price-card';card.innerHTML=`<h3>${esc(t(cat==='electro'?'electro':cat,u(cat)))}</h3><table><thead><tr><th>${esc(u('service'))}</th><th>${esc(u('price'))}</th></tr></thead><tbody></tbody></table>`;const tbody=card.querySelector('tbody');rows.forEach(s=>{const tr=document.createElement('tr'),td1=document.createElement('td'),td2=document.createElement('td');td1.textContent=serviceName(s.item_key,s.default_name);const raw=Number(localPrices[code]?.[s.item_key]??0);if(s.item_key==='report'&&raw===0){td2.textContent=t('by_scope','dle rozsahu');}else{const net=raw;const gross=country.vat_rate>0?net*(1+Number(country.vat_rate)):net;td2.textContent=mode==='gross'?fmt(gross,country.currency)+(s.unit||''):mode==='both'?`${fmt(net,country.currency)}${s.unit||''} / ${fmt(gross,country.currency)}${s.unit||''}`:fmt(net,country.currency)+(s.unit||'');}tr.append(td1,td2);tbody.append(tr);});grid.append(card);}}
  $('#price-country').addEventListener('change',e=>{localStorage.setItem('wond-country',e.target.value);renderPrices();});$('#vat-mode').addEventListener('change',renderPrices);
  const keys=['hero_title','hero_text','services_title','services_lead','electro','electro_text','water','water_text','assembly','assembly_text','building','building_text','company_title','company_lead','management','director_name','director_role','director_text','why_title','why_1','why_2','why_3','why_4','why_5','process_title','process_1','process_2','process_3','process_4','prices_title','prices_lead','notice','area','gallery_title','gallery_lead','contact_title'];
  async function init(){setLang(lang);if(!sb){$('#admin-config-warning').hidden=false;$('#admin-config-warning').textContent=t('not_configured');return;}const {data:{session:s}}=await sb.auth.getSession();session=s;if(session)await loadProfile();sb.auth.onAuthStateChange((_e,sess)=>{session=sess;setTimeout(loadProfile,0);});await loadPublic();}
  async function loadPublic(){const {data:c}=await sb.from('site_content').select('lang,content_key,content_value');(c||[]).forEach(x=>{if(WOND_TRANSLATIONS[x.lang])WOND_TRANSLATIONS[x.lang][x.content_key]=x.content_value;});const {data:co}=await sb.from('countries').select('*').order('sort_order');if(co?.length)countries=co;const {data:ct}=await sb.from('country_translations').select('*');(ct||[]).forEach(x=>{window.WOND_COUNTRY_NAMES[x.lang]??={};window.WOND_COUNTRY_NAMES[x.lang][x.country_code]=x.name;});const {data:si}=await sb.from('service_items').select('*').order('sort_order');if(si?.length)services=si;const {data:st}=await sb.from('service_translations').select('*');if(st?.length){translations={};st.forEach(x=>(translations[x.item_key]??={})[x.lang]=x.name);}const {data:cp}=await sb.from('country_prices').select('country_code,item_key,price,active');if(cp?.length){localPrices={};cp.forEach(x=>(localPrices[x.country_code]??={})[x.item_key]=Number(x.price));}setLang(lang);const {data:g}=await sb.from('gallery_items').select('*').eq('active',true).order('sort_order');if(g?.length)renderGallery(g);}
  function renderGallery(items){const box=$('#gallery-grid');box.innerHTML='';items.forEach(i=>{const f=document.createElement('figure'),img=document.createElement('img'),cap=document.createElement('figcaption');img.loading='lazy';img.src=sb.storage.from(cfg.bucket).getPublicUrl(i.storage_path).data.publicUrl;img.alt=i.alt_text||i.title||'WOND';cap.textContent=i.title||'WOND';f.append(img,cap);box.append(f);});}
  async function loadProfile(){if(!session){profile=null;$('#auth-card').hidden=false;$('#admin-panel').hidden=true;return;}const {data}=await sb.from('profiles').select('*').eq('id',session.user.id).maybeSingle();profile=data;$('#auth-card').hidden=true;$('#admin-panel').hidden=false;$('#admin-user-email').textContent=session.user.email;$('#admin-role').textContent=data?.role||'admin';$('#users-tab').hidden=data?.role!=='owner';await loadAdmin();}
  async function loadAdmin(){await renderAdminGallery();if(profile?.role==='owner')await renderUsers();buildContentEditor();await loadPriceEditor();await loadTranslationEditor();}
  function msg(text,err=false){$('#admin-message').textContent=text;$('#admin-message').style.color=err?'#b42318':'';}
  $('#login-btn').onclick=async()=>{if(!sb)return msg(t('not_configured'),true);const {error}=await sb.auth.signInWithPassword({email:$('#auth-email').value.trim(),password:$('#auth-password').value});$('#auth-message').textContent=error?error.message:t('saved');};
  $('#signup-btn').onclick=async()=>{if(!sb)return msg(t('not_configured'),true);const email=$('#auth-email').value.trim(),password=$('#auth-password').value;if(!email||password.length<8)return $('#auth-message').textContent='E-mail and password must be valid (minimum 8 characters).';const {data,error}=await sb.auth.signUp({email,password});if(error)return $('#auth-message').textContent=error.message;const {data:claim}=await sb.rpc('claim_owner');$('#auth-message').textContent=claim?'Owner created.':'Account created. Confirm e-mail if required, then sign in.';};
  $('#logout-btn').onclick=async()=>{await sb.auth.signOut();location.reload();};
  $$('.admin-tabs button').forEach(b=>b.onclick=()=>{$$('.admin-tabs button').forEach(x=>x.classList.remove('active'));$$('.admin-tab').forEach(x=>x.hidden=true);b.classList.add('active');$('#'+b.dataset.tab).hidden=false;});
  async function renderAdminGallery(){const {data}=await sb.from('gallery_items').select('*').order('sort_order');const box=$('#admin-gallery-items');box.innerHTML='';(data||[]).forEach(i=>{const row=document.createElement('div');row.className='admin-item';row.innerHTML=`<img src="${sb.storage.from(cfg.bucket).getPublicUrl(i.storage_path).data.publicUrl}" alt=""><div class="admin-item-body"><strong>${esc(i.title||'WOND')}</strong><button class="btn ghost dark" data-id="${i.id}">${esc(t('delete'))}</button></div>`;row.querySelector('button').onclick=async()=>{await sb.storage.from(cfg.bucket).remove([i.storage_path]);await sb.from('gallery_items').delete().eq('id',i.id);await renderAdminGallery();await loadPublic();};box.append(row);});}
  $('#upload-btn').onclick=async()=>{const files=[...$('#photo-files').files];if(!files.length)return msg(t('select_files'),true);for(const file of files){const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]+/gi,'-');const path=`${crypto.randomUUID()}-${safe}`;const up=await sb.storage.from(cfg.bucket).upload(path,file,{upsert:false,contentType:file.type});if(up.error)return msg(up.error.message,true);const ins=await sb.from('gallery_items').insert({storage_path:path,title:$('#photo-title').value.trim()||file.name,alt_text:$('#photo-alt').value.trim()||file.name,sort_order:Date.now()});if(ins.error)return msg(ins.error.message,true);}$('#photo-files').value='';msg(t('saved'));await renderAdminGallery();await loadPublic();};
  function buildContentEditor(){const sel=$('#content-lang');if(!sel.options.length)langs.forEach(l=>{const o=document.createElement('option');o.value=l;o.textContent=WOND_TRANSLATIONS[l].name;sel.append(o);});sel.value=lang;sel.onchange=()=>fillContent(sel.value);fillContent(sel.value);}
  async function fillContent(l){const {data}=await sb.from('site_content').select('content_key,content_value').eq('lang',l);const map=Object.fromEntries((data||[]).map(x=>[x.content_key,x.content_value]));const box=$('#content-editor');box.innerHTML='';keys.forEach(k=>{const lab=document.createElement('label');lab.textContent=k;const ta=document.createElement('textarea');ta.dataset.key=k;ta.value=map[k] ?? (WOND_TRANSLATIONS[l]?.[k]||'');lab.append(ta);box.append(lab);});}
  $('#save-content').onclick=async()=>{const l=$('#content-lang').value;const rows=$$('#content-editor textarea').map(x=>({lang:l,content_key:x.dataset.key,content_value:x.value,updated_at:new Date().toISOString()}));const {error}=await sb.from('site_content').upsert(rows,{onConflict:'lang,content_key'});msg(error?error.message:t('saved'),!!error);if(!error){rows.forEach(r=>{if(WOND_TRANSLATIONS[r.lang])WOND_TRANSLATIONS[r.lang][r.content_key]=r.content_value;});if(l===lang)setLang(lang);}};
  function buildCountryAdminSelect(){const sel=$('#admin-price-country');if(!sel)return;const cur=sel.value||'CZ';sel.innerHTML='';countries.forEach(c=>{const o=document.createElement('option');o.value=c.code;o.textContent=`${countryName(c.code)} — ${c.currency}`;sel.append(o);});sel.value=countries.some(c=>c.code===cur)?cur:'CZ';sel.onchange=()=>fillPriceEditor(sel.value);}
  async function loadPriceEditor(){buildCountryAdminSelect();await fillPriceEditor($('#admin-price-country').value);}
  async function fillPriceEditor(countryCode){const {data}=await sb.from('country_prices').select('country_code,item_key,price,active').eq('country_code',countryCode);const map=Object.fromEntries((data||[]).map(x=>[x.item_key,x]));const box=$('#price-editor');box.innerHTML='';const byCat={};services.forEach(s=>(byCat[s.category]??=[]).push(s));Object.entries(byCat).forEach(([cat,rows])=>{const h=document.createElement('h3');h.textContent=t(cat==='electro'?'electro':cat,cat);box.append(h);rows.forEach(s=>{const wrap=document.createElement('label');wrap.className='price-edit-row';wrap.innerHTML=`<span>${esc(serviceName(s.item_key,s.default_name))}${s.unit?` (${esc(s.unit)})`:''}</span><input type="number" step="0.01" min="0" data-key="${esc(s.item_key)}" value="${map[s.item_key]?.price??localPrices[countryCode]?.[s.item_key]??0}">`;box.append(wrap);});});}
  $('#save-prices').onclick=async()=>{const countryCode=$('#admin-price-country').value;const rows=$$('#price-editor input').map(i=>({country_code:countryCode,item_key:i.dataset.key,price:Number(i.value),active:true,updated_at:new Date().toISOString()}));const {error}=await sb.from('country_prices').upsert(rows,{onConflict:'country_code,item_key'});msg(error?error.message:t('saved'),!!error);if(!error){localPrices[countryCode]??={};rows.forEach(r=>localPrices[countryCode][r.item_key]=r.price);renderPrices();}};
  async function loadTranslationEditor(){const langSel=$('#translation-lang');if(!langSel.options.length)langs.forEach(l=>{const o=document.createElement('option');o.value=l;o.textContent=WOND_TRANSLATIONS[l].name;langSel.append(o);});langSel.value=lang;langSel.onchange=()=>fillTranslationEditor(langSel.value);await fillTranslationEditor(langSel.value);}
  async function fillTranslationEditor(l){const {data}=await sb.from('service_translations').select('item_key,name').eq('lang',l);const map=Object.fromEntries((data||[]).map(x=>[x.item_key,x.name]));const box=$('#translation-editor');box.innerHTML='';services.forEach(s=>{const lab=document.createElement('label');lab.className='price-edit-row';lab.innerHTML=`<span>${esc(s.item_key)} — ${esc(s.category)}</span><input type="text" data-key="${esc(s.item_key)}" value="${esc(map[s.item_key]??translations[s.item_key]?.[l]??s.default_name)}">`;box.append(lab);});}
  $('#save-translations').onclick=async()=>{const l=$('#translation-lang').value;const rows=$$('#translation-editor input').map(i=>({item_key:i.dataset.key,lang:l,name:i.value.trim()})).filter(x=>x.name);const {error}=await sb.from('service_translations').upsert(rows,{onConflict:'item_key,lang'});msg(error?error.message:t('saved'),!!error);if(!error){translations={...translations};rows.forEach(r=>(translations[r.item_key]??={})[r.lang]=r.name);renderPrices();}};
  async function renderUsers(){const {data}=await sb.from('profiles').select('id,email,role,created_at').order('created_at');const box=$('#users-list');box.innerHTML='';(data||[]).forEach(u=>{const row=document.createElement('div');row.className='admin-item';row.innerHTML=`<div class="admin-item-body"><strong>${esc(u.email)}</strong><span class="muted">${esc(u.role)}</span></div>`;if(u.role!=='owner'){const b=document.createElement('button');b.className='btn ghost dark';b.textContent=t('delete');b.onclick=async()=>{const r=await sb.functions.invoke('delete-admin',{body:{user_id:u.id}});msg(r.error?r.error.message:t('saved'),!!r.error);await renderUsers();};row.querySelector('.admin-item-body').append(b);}box.append(row);});}
  $('#add-admin').onclick=async()=>{const email=$('#new-admin-email').value.trim(),password=$('#new-admin-password').value;if(!email||password.length<8)return msg('Enter e-mail and a password of at least 8 characters.',true);const r=await sb.functions.invoke('create-admin',{body:{email,password}});msg(r.error?r.error.message:t('saved'),!!r.error);if(!r.error){$('#new-admin-email').value='';$('#new-admin-password').value='';await renderUsers();}};
  function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[init();
})();
(() => {
