const C={
 CZ:{name:'Česko',currency:'Kč',vat:.21, cities:['Brno','Praha','Ostrava','Plzeň','Olomouc','Kuřim','Rosice','Ivančice','Židlochovice','Blansko','Vyškov']},
 SI:{name:'Slovenija',currency:'€',vat:.22,cities:['Ljubljana','Maribor','Celje','Kranj','Koper','Novo mesto','Ptuj','Murska Sobota','Nova Gorica']},
 SK:{name:'Slovensko',currency:'€',vat:.23,cities:['Bratislava','Košice','Prešov','Žilina','Nitra','Trnava','Trenčín']},
 DE:{name:'Deutschland',currency:'€',vat:.19,cities:['Berlin','München','Hamburg','Köln','Frankfurt','Stuttgart','Dresden']},
 PL:{name:'Polska',currency:'zł',vat:.23,cities:['Warszawa','Kraków','Wrocław','Poznań','Gdańsk','Katowice']},
 HU:{name:'Magyarország',currency:'Ft',vat:.27,cities:['Budapest','Debrecen','Szeged','Pécs','Győr']},
 HR:{name:'Hrvatska',currency:'€',vat:.25,cities:['Zagreb','Split','Rijeka','Osijek','Zadar']},
 RO:{name:'România',currency:'lei',vat:.21,cities:['București','Cluj-Napoca','Timișoara','Iași','Brașov']},
 UA:{name:'Україна',currency:'₴',vat:.20,cities:['Київ','Львів','Ужгород','Одеса','Івано-Франківськ','Чернівці']},
 GB:{name:'United Kingdom',currency:'£',vat:.20,cities:['London','Birmingham','Manchester','Leeds','Bristol']}
};
const BASE=[
 ['Elektroinstalace',[['Elektro bod (zásuvka / vypínač)',450,'Št'],['Další elektro bod',350,'Št'],['Světelný bod',350,'Št'],['Uložení kabelu v trubce',90,'M'],['Sekání a zapravení drážky',120,'M'],['Rozvodná deska + přípojka',5500,'Št']]],
 ['Voda a kanalizace',[['PPR potrubí',180,'M'],['ALUPEX potrubí',220,'M'],['Kanalizační potrubí',250,'M'],['Vodní bod teplá + studená',650,'Št'],['Dvojitý vodní bod',1100,'Št'],['Přípoj na vodu',800,'Št']]],
 ['Rozvaděče a ochrany',[['Rozvaděč 24 modulů',11000,'Št'],['Rozvaděč 36 modulů',14000,'Št'],['Rozvaděč 48 modulů',18000,'Št'],['Rozvaděč 72 modulů',25000,'Št'],['Přepěťová ochrana',1200,'Št']]],
 ['Kontroly a revize',[['Základní kontrola elektroinstalace',1200,'Št'],['Vizuální kontrola',900,'Št'],['Revizní zpráva',0,'']]],
 ['Výjezd',[['Výjezd na místo do 50 km',500,'Št']]]
];
const $=s=>document.querySelector(s);let data={};
function fmt(n,code){return new Intl.NumberFormat(code==='CZ'?'cs-CZ':code==='UA'?'uk-UA':code==='PL'?'pl-PL':code==='HU'?'hu-HU':code==='RO'?'ro-RO':'de-DE',{maximumFractionDigits:0}).format(n);}
function renderPrices(){const code=$('#priceCountry').value,city=$('#priceCity').value,mode=$('#vatMode').value,c=C[code];$('#priceMeta').textContent=`${city} · ${c.name} · DPH ${Math.round(c.vat*100)}%`;const html=BASE.map(([cat,items])=>`<tr style="background:var(--bg)"><td colspan=4 style="font-weight:600;padding:0.75rem;color:var(--ink)">${cat}</td></tr>${items.map(([desc,price,unit])=>{let final=price;if(mode==='with') final=Math.round(price*(1+c.vat));else if(mode==='both'){const wvat=Math.round(price*(1+c.vat));return `<tr><td style="padding:0.5rem">${desc}</td><td style="padding:0.5rem;text-align:right">${fmt(price,code)} ${c.currency}</td><td style="padding:0.5rem;text-align:right">${fmt(wvat,code)} ${c.currency}</td><td style="padding:0.5rem;text-align:center">${unit}</td></tr>`;}return `<tr><td style="padding:0.5rem">${desc}</td><td style="padding:0.5rem;text-align:right">${fmt(final,code)} ${c.currency}</td><td></td><td style="padding:0.5rem;text-align:center">${unit}</td></tr>`;}).join('')}`).join('');$('#priceTable').innerHTML=`<table style="width:100%;border-collapse:collapse;font-size:0.9rem">${html}</table>`;}function init(){Object.entries(C).forEach(([k,v])=>$('#priceCountry').insertAdjacentHTML('beforeend',`<option value="${k}">${v.name}</option>`));$('#priceCountry').value='CZ';function cities(){const code=$('#priceCountry').value;$('#priceCity').innerHTML='';C[code].cities.forEach(c=>$('#priceCity').insertAdjacentHTML('beforeend',`<option value="${c}">${c}</option>`));$('#priceCity').value=C[code].cities[0];renderPrices();}cities();$('#priceCountry').addEventListener('change',cities);$('#priceCity').addEventListener('change',renderPrices);$('#vatMode').addEventListener('change',renderPrices);renderPrices();}
async function loadSupabase(){try{const sb=window.supabase.createClient(WOND_SUPABASE.url,WOND_SUPABASE.anonKey);const {data:media,error:mediaError}=await sb.from('site_media').select('*').eq('slot','main_photo').single();if(mediaError) console.warn('Media load:', mediaError.message);if(media?.public_url){const img=$('#heroImage');if(img) img.src=media.public_url;}const {data:docs,error:docsError}=await sb.from('country_documents').select('*').eq('published',true).order('country_code');if(docsError) console.warn('Docs load:', docsError.message);if(docs&&docs.length>0){const gallery=$('#gallery');if(gallery){const html=docs.map(d=>`<div style="margin:1rem 0"><a href="${d.public_url}" target="_blank" style="color:var(--accent);text-decoration:none"><strong>${d.country_code}</strong> — ${d.title}</a></div>`).join('');gallery.insertAdjacentHTML('beforeend',`<div style="margin-top:2rem">${html}</div>`);}}}catch(e){console.error('Supabase error:',e);}}
window.addEventListener('load',()=>{init();loadSupabase();document.getElementById('year').textContent=new Date().getFullYear();});
