create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'admin' check (role in ('owner','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.countries (
  code text primary key,
  default_name text not null,
  currency text not null,
  vat_rate numeric(6,4) not null default 0,
  active boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.country_translations (
  country_code text not null references public.countries(code) on delete cascade,
  lang text not null,
  name text not null,
  primary key(country_code, lang)
);

create table if not exists public.service_items (
  id bigint generated by default as identity primary key,
  category text not null,
  item_key text not null unique,
  default_name text not null,
  unit text not null default '',
  sort_order integer not null default 0,
  active boolean not null default true
);

create table if not exists public.service_translations (
  item_key text not null references public.service_items(item_key) on delete cascade,
  lang text not null,
  name text not null,
  primary key(item_key, lang)
);

create table if not exists public.country_prices (
  country_code text not null references public.countries(code) on delete cascade,
  item_key text not null references public.service_items(item_key) on delete cascade,
  price numeric(12,2) not null default 0,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key(country_code, item_key)
);

create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  lang text not null,
  content_key text not null,
  content_value text not null default '',
  updated_at timestamptz not null default now(),
  unique(lang, content_key)
);

create table if not exists public.gallery_items (
  id uuid primary key default gen_random_uuid(),
  storage_path text not null unique,
  title text not null default '',
  alt_text text not null default '',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role in ('owner','admin')); $$;
create or replace function public.is_owner() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='owner'); $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,role) values(new.id,coalesce(new.email,''),'admin') on conflict(id) do update set email=excluded.email; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.claim_owner() returns boolean language plpgsql security definer set search_path=public as $$ declare claimed boolean; begin if auth.uid() is null then return false; end if; perform pg_advisory_xact_lock(9012401); if exists(select 1 from public.profiles where role='owner') then return false; end if; update public.profiles set role='owner' where id=auth.uid(); select exists(select 1 from public.profiles where id=auth.uid() and role='owner') into claimed; return claimed; end; $$;
grant execute on function public.claim_owner() to authenticated;

grant usage on schema public to anon, authenticated;
grant select on public.countries, public.country_translations, public.service_items, public.service_translations, public.country_prices, public.site_content, public.gallery_items to anon, authenticated;
grant select on public.profiles to authenticated;
grant insert,update,delete on public.countries, public.country_translations, public.service_items, public.service_translations, public.country_prices, public.site_content, public.gallery_items to authenticated;

alter table public.profiles enable row level security;
alter table public.countries enable row level security;
alter table public.country_translations enable row level security;
alter table public.service_items enable row level security;
alter table public.service_translations enable row level security;
alter table public.country_prices enable row level security;
alter table public.site_content enable row level security;
alter table public.gallery_items enable row level security;

-- Політики безпеки (RLS)
drop policy if exists profiles_self_or_owner on public.profiles; create policy profiles_self_or_owner on public.profiles for select to authenticated using(id=auth.uid() or public.is_owner());
drop policy if exists countries_public_read on public.countries; create policy countries_public_read on public.countries for select to anon,authenticated using(active=true or public.is_admin());
drop policy if exists countries_admin_write on public.countries; create policy countries_admin_write on public.countries for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists country_translations_public_read on public.country_translations; create policy country_translations_public_read on public.country_translations for select to anon,authenticated using(true);
drop policy if exists country_translations_admin_write on public.country_translations; create policy country_translations_admin_write on public.country_translations for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists service_items_public_read on public.service_items; create policy service_items_public_read on public.service_items for select to anon,authenticated using(active=true or public.is_admin());
drop policy if exists service_items_admin_write on public.service_items; create policy service_items_admin_write on public.service_items for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists service_translations_public_read on public.service_translations; create policy service_translations_public_read on public.service_translations for select to anon,authenticated using(true);
drop policy if exists service_translations_admin_write on public.service_translations; create policy service_translations_admin_write on public.service_translations for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists country_prices_public_read on public.country_prices; create policy country_prices_public_read on public.country_prices for select to anon,authenticated using(active=true or public.is_admin());
drop policy if exists country_prices_admin_write on public.country_prices; create policy country_prices_admin_write on public.country_prices for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists content_public_read on public.site_content; create policy content_public_read on public.site_content for select to anon,authenticated using(true);
drop policy if exists content_admin_write on public.site_content; create policy content_admin_write on public.site_content for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists gallery_public_read on public.gallery_items; create policy gallery_public_read on public.gallery_items for select to anon,authenticated using(active=true or public.is_admin());
drop policy if exists gallery_admin_write onpublic.gallery_items; create policy gallery_admin_write on public.gallery_items for all to authenticated using(public.is_admin()) with check(public.is_admin());

insert into storage.buckets(id,name,public) values('wond-gallery','wond-gallery',true) on conflict(id) do update set public=true;
drop policy if exists gallery_storage_public_read on storage.objects; create policy gallery_storage_public_read on storage.objects for select to public using(bucket_id='wond-gallery');
drop policy if exists gallery_storage_admin_insert on storage.objects; create policy gallery_storage_admin_insert on storage.objects for insert to authenticated with check(bucket_id='wond-gallery' and public.is_admin());
drop policy if exists gallery_storage_admin_update on storage.objects; create policy gallery_storage_admin_update on storage.objects for update to authenticated using(bucket_id='wond-gallery' and public.is_admin()) with check(bucket_id='wond-gallery' and public.is_admin());
drop policy if exists gallery_storage_admin_delete on storage.objects; create policy gallery_storage_admin_delete on storage.objects for delete to authenticated using(bucket_id='wond-gallery' and public.is_admin());

-- Додавання країн (з виправленими одинарними лапками)[span_3](start_span)[span_3](end_span)
insert into public.countries(code,default_name,currency,vat_rate,sort_order) values('CZ','Česko','CZK',0.21,0) on conflict(code) do update set default_name=excluded.default_name,currency=excluded.currency,vat_rate=excluded.vat_rate,sort_order=excluded.sort_order,active=true;
insert into public.countries(code,default_name,currency,vat_rate,sort_order) values('UA','Україна','UAH',0.20,1) on conflict(code) do update set default_name=excluded.default_name,currency=excluded.currency,vat_rate=excluded.vat_rate,sort_order=excluded.sort_order,active=true;
insert into public.countries(code,default_name,currency,vat_rate,sort_order) values('SI','Slovenija','EUR',0.22,2) on conflict(code) do update set default_name=excluded.default_name,currency=excluded.currency,vat_rate=excluded.vat_rate,sort_order=excluded.sort_order,active=true;
insert into public.countries(code,default_name,currency,vat_rate,sort_order) values('SK','Slovensko','EUR',0.23,3) on conflict(code) do update set default_name=excluded.default_name,currency=excluded.currency,vat_rate=excluded.vat_rate,sort_order=excluded.sort_order,active=true;
insert into public.countries(code,default_name,currency,vat_rate,sort_order) values('DE','Deutschland','EUR',0.19,4) on conflict(code) do update set default_name=excluded.default_name,currency=excluded.currency,vat_rate=excluded.vat_rate,sort_order=excluded.sort_order,active=true;
insert into public.countries(code,default_name,currency,vat_rate,sort_order) values('PL','Polska','PLN',0.23,5) on conflict(code) do update set default_name=excluded.default_name,currency=excluded.currency,vat_rate=excluded.vat_rate,sort_order=excluded.sort_order,active=true;
insert into public.countries(code,default_name,currency,vat_rate,sort_order) values('RO','România','RON',0.21,6) on conflict(code) do update set default_name=excluded.default_name,currency=excluded.currency,vat_rate=excluded.vat_rate,sort_order=excluded.sort_order,active=true;
insert into public.countries(code,default_name,currency,vat_rate,sort_order) values('HU','Magyarország','HUF',0.27,7) on conflict(code) do update set default_name=excluded.default_name,currency=excluded.currency,vat_rate=excluded.vat_rate,sort_order=excluded.sort_order,active=true;
insert into public.countries(code,default_name,currency,vat_rate,sort_order) values('HR','Hrvatska','EUR',0.25,8) on conflict(code) do update set default_name=excluded.default_name,currency=excluded.currency,vat_rate=excluded.vat_rate,sort_order=excluded.sort_order,active=true;
insert into public.countries(code,default_name,currency,vat_rate,sort_order) values('GB','United Kingdom','GBP',0.20,9) on conflict(code) do update set default_name=excluded.default_name,currency=excluded.currency,vat_rate=excluded.vat_rate,sort_order=excluded.sort_order,active=true;
