-- WOND production Supabase schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'admin' check (role in ('owner','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  lang text not null,
  content_key text not null,
  content_value text not null default '',
  updated_at timestamptz not null default now(),
  unique(lang, content_key)
);

create table if not exists public.price_items (
  id bigint generated by default as identity primary key,
  category text not null,
  item_key text not null,
  name text not null,
  unit text not null default '',
  price numeric(12,2) not null default 0,
  currency text not null default 'CZK',
  sort_order integer not null default 0,
  active boolean not null default true,
  unique(category, item_key)
);

create table if not exists public.gallery_items (
  id uuid primary key default gen_random_uuid(),
  storage_path text not null unique,
  title text not null default '',
  alt_text text not null default '',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('owner','admin'));
$$;

create or replace function public.is_owner()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'owner');
$$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id,email,role) values(new.id, coalesce(new.email,''), 'admin')
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.claim_owner()
returns boolean language plpgsql security definer set search_path = public as $$
declare claimed boolean;
begin
  if auth.uid() is null then return false; end if;
  perform pg_advisory_xact_lock(9012401);
  if exists(select 1 from public.profiles where role='owner') then return false; end if;
  update public.profiles set role='owner' where id=auth.uid();
  select exists(select 1 from public.profiles where id=auth.uid() and role='owner') into claimed;
  return claimed;
end;
$$;

grant execute on function public.claim_owner() to authenticated;

grant usage on schema public to anon, authenticated;
grant select on public.gallery_items to anon, authenticated;
grant select on public.site_content to anon, authenticated;
grant select on public.price_items to anon, authenticated;
grant select on public.profiles to authenticated;
grant insert, update, delete on public.gallery_items to authenticated;
grant insert, update, delete on public.site_content to authenticated;
grant insert, update, delete on public.price_items to authenticated;

alter table public.profiles enable row level security;
alter table public.site_content enable row level security;
alter table public.price_items enable row level security;
alter table public.gallery_items enable row level security;

drop policy if exists profiles_self_or_owner on public.profiles;
create policy profiles_self_or_owner on public.profiles for select to authenticated using (id=auth.uid() or public.is_owner());

drop policy if exists content_public_read on public.site_content;
create policy content_public_read on public.site_content for select to anon, authenticated using (true);
drop policy if exists content_admin_write on public.site_content;
create policy content_admin_write on public.site_content for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists prices_public_read on public.price_items;
create policy prices_public_read on public.price_items for select to anon, authenticated using (active=true or public.is_admin());
drop policy if exists prices_admin_write on public.price_items;
create policy prices_admin_write on public.price_items for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists gallery_public_read on public.gallery_items;
create policy gallery_public_read on public.gallery_items for select to anon, authenticated using (active=true or public.is_admin());
drop policy if exists gallery_admin_write on public.gallery_items;
create policy gallery_admin_write on public.gallery_items for all to authenticated using (public.is_admin()) with check (public.is_admin());

insert into storage.buckets(id,name,public) values('wond-gallery','wond-gallery',true)
on conflict (id) do update set public=true;

drop policy if exists gallery_storage_public_read on storage.objects;
create policy gallery_storage_public_read on storage.objects for select to public using (bucket_id='wond-gallery');
drop policy if exists gallery_storage_admin_insert on storage.objects;
create policy gallery_storage_admin_insert on storage.objects for insert to authenticated with check (bucket_id='wond-gallery' and public.is_admin());
drop policy if exists gallery_storage_admin_update on storage.objects;
create policy gallery_storage_admin_update on storage.objects for update to authenticated using (bucket_id='wond-gallery' and public.is_admin()) with check (bucket_id='wond-gallery' and public.is_admin());
drop policy if exists gallery_storage_admin_delete on storage.objects;
create policy gallery_storage_admin_delete on storage.objects for delete to authenticated using (bucket_id='wond-gallery' and public.is_admin());
